apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: retail-observability-alerts
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
    - name: retail-pod-alerts
      rules:

        - alert: OrdersDeploymentDown
          expr: |
            kube_deployment_status_replicas_available{
              namespace="retail",
              deployment="orders-v1"
            } < 1
          for: 1m
          labels:
            severity: critical
            team: devops
          annotations:
            summary: "Orders deployment is down"
            description: "Orders deployment has no available replicas for more than 1 minute."

        - alert: RetailPodCrashLooping
          expr: |
            rate(
              kube_pod_container_status_restarts_total{
                namespace="retail"
              }[5m]
            ) > 0
          for: 5m
          labels:
            severity: critical
            team: devops
          annotations:
            summary: "Retail pod is restarting"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} container {{ $labels.container }} is repeatedly restarting."

        - alert: RetailHPAAtMaxReplicas
          expr: |
            kube_horizontalpodautoscaler_status_current_replicas{
              namespace="retail"
            }
            >=
            kube_horizontalpodautoscaler_spec_max_replicas{
              namespace="retail"
            }
          for: 2m
          labels:
            severity: warning
            team: devops
          annotations:
            summary: "Retail HPA has reached maximum replicas"
            description: "HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler }} has reached its maximum replica count."

        - alert: RetailHighCPU
          expr: |
            (
              sum by (namespace, pod) (
                rate(
                  container_cpu_usage_seconds_total{
                    namespace="retail",
                    container!="",
                    container!="POD"
                  }[5m]
                )
              )
              /
              sum by (namespace, pod) (
                kube_pod_container_resource_requests{
                  namespace="retail",
                  resource="cpu"
                }
              )
            ) > 0.80
          for: 2m
          labels:
            severity: warning
            team: devops
          annotations:
            summary: "High CPU usage"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is using more than 80% of requested CPU."
