# apiVersion: networking.istio.io/v1
# kind: DestinationRule
# metadata:
#   name: orders
#   namespace: retail
# spec:
#   host: orders

#   trafficPolicy:
#     loadBalancer:
#       simple: ROUND_ROBIN

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: orders
  namespace: retail
spec:
  host: orders

  subsets:
    - name: v1
      labels:
        app: orders
        version: v1

    - name: v2
      labels:
        app: orders
        version: v2

  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
