# apiVersion: networking.istio.io/v1
# kind: VirtualService
# metadata:
#   name: orders
#   namespace: retail
# spec:
#   hosts:
#     - orders

#   http:
#     - route:
#         - destination:
#             host: orders
#             port:
#               number: 80

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: orders
  namespace: retail

spec:
  hosts:
    - orders

  http:
    - route:
        - destination:
            host: orders
            subset: v1
            port:
              number: 80
          weight: 90

        - destination:
            host: orders
            subset: v2
            port:
              number: 80
          weight: 10
