# k8s/istio/virtualservice.yaml

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: retail-ui
  namespace: retail

spec:
  hosts:
    - retail.metatechz.store

  gateways:
    - retail-gateway

  http:

    - name: ui-route

      match:
        - uri:
            prefix: /

      route:
        - destination:
            host: ui.retail.svc.cluster.local
            port:
              number: 8080

          weight: 100

      timeout: 30s

      retries:
        attempts: 3
        perTryTimeout: 5s
        retryOn: connect-failure,reset,503,504
