apiVersion: v1
kind: Secret
metadata:
  name: retail-secrets
  namespace: retail
type: Opaque
stringData:

  DB_PASSWORD: "CHANGE-ME-STRONG-PASSWORD"

  RABBITMQ_PASSWORD: "CHANGE-ME-STRONG-RABBITMQ-PASSWORD"
