apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: retail

spec:

  type: ClusterIP

  selector:
    app: orders-db

  ports:

    - name: postgres
      port: 5432
      targetPort: 5432


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-db
  namespace: retail

spec:

  serviceName: orders-db

  replicas: 1

  selector:
    matchLabels:
      app: orders-db

  template:

    metadata:
      labels:
        app: orders-db

    spec:

      terminationGracePeriodSeconds: 60

      containers:

        - name: postgres

          image: postgres:16

          ports:

            - name: postgres
              containerPort: 5432

          env:

            - name: POSTGRES_DB
              value: orders

            - name: POSTGRES_USER
              value: orders_user

            - name: POSTGRES_PASSWORD

              valueFrom:
                secretKeyRef:
                  name: retail-secrets
                  key: DB_PASSWORD

          resources:

            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: "1"
              memory: 1Gi

          startupProbe:

            exec:

              command:
                - pg_isready
                - -U
                - orders_user
                - -d
                - orders

            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:

            exec:

              command:
                - pg_isready
                - -U
                - orders_user
                - -d
                - orders

            periodSeconds: 10

          livenessProbe:

            exec:

              command:
                - pg_isready
                - -U
                - orders_user
                - -d
                - orders

            initialDelaySeconds: 60
            periodSeconds: 20

          volumeMounts:

            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:

    - metadata:
        name: postgres-data

      spec:

        accessModes:
          - ReadWriteOnce

        storageClassName: gp3

        resources:

          requests:
            storage: 20Gi
