apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: retail

  labels:
    app: catalog

spec:

  replicas: 1

  revisionHistoryLimit: 5

  strategy:

    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: catalog

  template:

    metadata:
      labels:
        app: catalog

    spec:

      terminationGracePeriodSeconds: 30

      topologySpreadConstraints:

        - maxSkew: 1

          topologyKey: topology.kubernetes.io/zone

          whenUnsatisfiable: ScheduleAnyway

          labelSelector:
            matchLabels:
              app: catalog

      affinity:

        podAntiAffinity:

          preferredDuringSchedulingIgnoredDuringExecution:

            - weight: 100

              podAffinityTerm:

                topologyKey: kubernetes.io/hostname

                labelSelector:
                  matchLabels:
                    app: catalog

      containers:

        - name: catalog

          image: 302524629943.dkr.ecr.us-east-1.amazonaws.com/catalog:latest

          imagePullPolicy: Always

          ports:

            - name: http
              containerPort: 8080

          envFrom:

            - configMapRef:
                name: catalog-config

          env:

            - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD

              valueFrom:
                secretKeyRef:
                  name: retail-secrets
                  key: DB_PASSWORD

          resources:

            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 512Mi

          startupProbe:

            httpGet:
              path: /health
              port: http

            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:

            httpGet:
              path: /health
              port: http

            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:

            httpGet:
              path: /health
              port: http

            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
